name: Edgeware Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: actions/cache@v1.1.2
      with:
        path: target
        key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-
    - run: bash setup.sh
    - id: create_archive
      run: |
        ARCHIVE=edgeware-$GITHUB_SHA-macos.tar.gz
        tar -czvf $ARCHIVE -C target/release edgeware
        echo ::set-output name=ASSET::$ARCHIVE
